// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }


// app/(backoffice)/layout.tsx
// import type { Metadata } from "next";
// import BackofficeShell from "@/components/layout/BackofficeShell";

// export const metadata: Metadata = {
//   title: "Backoffice",
// };

// export default function BackofficeLayout({ children }: { children: React.ReactNode }) {
//   return <BackofficeShell>{children}</BackofficeShell>;
// }


// ----------
export const metadata = { title: "iMeeting Backoffice" };


export default function RootLayout({ children }: { children: React.ReactNode }) {
return (
<html lang="id">
  <head />
    <body>
    {children}
    </body>
</html>
);
}